require("dotenv").config();

const { Pool } = require("pg");

const dropTableRooms = "DROP TABLE IF EXISTS rooms";
const dropTableSongs = "DROP TABLE IF EXISTS songs";
const createTableRooms =
  "CREATE TABLE rooms (id_room INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name_room VARCHAR(64), url_room TEXT UNIQUE)";
const createTableSongs =
  "CREATE TABLE songs (id_song INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, id_room INT REFERENCES rooms ON DELETE CASCADE ON UPDATE CASCADE, name_song TEXT, url_song TEXT)";

async function main() {
  try {
    const pool = new Pool();
    await pool.query(dropTableSongs);
    await pool.query(dropTableRooms);
    await pool.query(createTableRooms);
    await pool.query(createTableSongs);
    await pool.end();
  } catch (error) {
    console.log(error);
  }
}
main();
